import "./globals.css";
import type { Metadata } from "next";
import { inter } from "./fonts";
import AOSInit from "@/config/aos-init";
import Modal from "@/components/ui/homepage/modal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${inter.className} min-h-screen`}>
        <Modal />
        {children}
      </body>
    </html>
  );
}
