import "./globals.css";
import type { Metadata } from "next";
import { inter } from "./fonts";
import AOSInit from "@/config/aos-init";
import Provider from "@/lib/provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${inter.className} min-h-screen`}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
