import "./globals.css";
import type { Metadata } from "next";
import { inter, merienda } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className={`${merienda.className}`}>Hello World</h1>
        <h3 className={`${inter.className} italic`}>Hello Next</h3>
        {children}
      </body>
    </html>
  );
}
